import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Monaco Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Monaco Editor</a>
        </h1>

        <div className={styles.grid}>
          <a
            href="https://microsoft.github.io/monaco-editor/"
            className={styles.card}
          >
            <h2>What is Monaco Editor &rarr;</h2>
            <p>
              Find in-depth information about Monaco Editor features and API.
            </p>
          </a>

          <a
            href="https://github.com/suren-atoyan/monaco-react"
            className={styles.card}
          >
            <h2>What is Monaco Editor React &rarr;</h2>
            <p>Learn about monaco-react!</p>
          </a>

          <a href="/monaco" className={styles.card}>
            <h2>Demo my Monaco &rarr;</h2>
            <p>Just playground</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
